language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - doxygen

script:
  - mkdir travis && cd travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DENABLE_COVERAGE=On -DSANITIZE_ADDRESS=On -DENABLE_TESTS=On -DBUILD_DOC_INTERNAL=On && make install && make test

after_success:
  - make gcov
  - bash <(curl -s https://codecov.io/bash) -X gcov
