language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

script:
  - mkdir travis && cd travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=../travis-install && make install
