language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

script:
  - mkdir travis && cd travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=../travis-install && make install
